### PR TITLE
Attempt to separate layer processing and gui components (draft)

### PR DESCRIPTION
**Pull request by mara004**

### CODE REVIEW

**Comment by mara004** [comment]
Uh, the history is also mixed up for this PR. How do I get things ordered again?

**Comment by cfcurtis** [comment]
Oh no, I'm sorry! I just merged the changes from main into layer_filter_improvements, so that branch should be up to date now. Does it help if you switch to that branch?

**Comment by mara004** [comment]
No problem. As far as I can see, the github gui doesn't have an option to rebase my wxless_layerfilter branch to layer_filter_improvements (it would probably be doable with the git command-line tool). Maybe I'll just close this PR and redo it to also include the recent modifications by @susiej

**Comment by mara004** [comment]
I'm closing this now and will make a new PR soon.

**Pull request closed without merging**
