### PR TITLE
Keep certain lines in parser

### PR DESCRIPTION
**Pull request by susiej**
So far i have tested in patterns from Jalie, Eli Monster, P4P, GG, SUAT, Sinclair and Pattern Niche. So far they have all worked.

### CODE REVIEW

**Comment by susiej** [comment]
hmm may have some extra Qs... I'll fix that up...

**Comment by susiej** [comment]
fixed

**Comment by cfcurtis** [comment]
I'll merge this in and give it a test, but I'm wondering if it's enough of a difference from the original implementation to warrant looping through the stream a second time. It seems like the main difference now is in removing extra Qs? That's something worth doing to be sure, and I also like the recursion for those cases.

**Comment by cfcurtis** [comment]
I also see you're removing the lingering layers in properties, that's a nice addition as well.

**Comment by susiej** [comment]
Where is my code looping through the stream a second time?

**Comment by cfcurtis** [comment]
Finally useful error messages, that's great.

In the original filter_content function I do the same thing - it keeps all the non-showing operators like font changes etc. It also keeps all q/Qs though so it ends up with a lot of empty q/Q blocks, but that way they're at least guaranteed to match.

For looping through a second time I mean calling first filter_content, and then remove_ocgs_from_stream.

**Comment by susiej** [comment]
Oh, also, the bit with argv and the bit in the mac spec are separate to layers, so branch them separately if they need more testing? Took me a sec to figure out why passing the file name to python wasn't automatically setting it as the input file :P

**Comment by susiej** [comment]
Ahh :)

**Comment by susiej** [comment]
I should have read your code more closely before :P. I had a bunch of pdfs where the ocg hadn't been removed from the stream, so I just assumed it wasn't trying to remove them. Sorry! I'll see what the difference is.

**Comment by susiej** [comment]
Hrm. How deep is yours going to look for streams? Mine goes 5 layers deep to look for streams. So far it fixed all the ones I've tested without going deeper. I found it took too long going deeper than 5, but if you come across a file that needs to look deeper, I can increase it. The script usually runs for me in less than 2 seconds. Which designer has a file that runs slower?

**Comment by cfcurtis** [comment]
Mine isn't actually checking past the initial stream, so that's probably what was missing for your test case.

On my 2009 MacBook many files take several minutes! A lot of users have old and slow computers so I'm trying to keep efficiency in mind.

**Comment by susiej** [comment]
Pulling out my old thinkpad T60 (2006) to see how it goes :). I’ll have to run a bunch of updates to even get it to see GitHub (https) hahaha. I’ll leave it updating whilst I’m out this morning. If you want I can see if I can get my old T40 (2003) running but that may not run python3... 
Assuming I don’t get a work call, I should be able to look this arvo. My work project went live on Monday, with so far nothing major broken *cross fingers*

**Comment by cfcurtis** [comment]
Good luck! The old MacBook was the only way I was able to build an app for Mac users, and I had to update to a hacked version of High Sierra to make it work (though even that keeps throwing me warnings that it's out of support). It turned out to be handy though - a low res screen to tweak the GUI plus slow processing to make sure it's accessible.

**Comment by susiej** [comment]
Hey, I still don’t think running my bit is that much of a speed issue. Finally managed to get the Thinkpad (2006) running to test it on a slow computer (had to reinstall Debian, then build wxpython which took hours :P).

I found a slow pdf (SUAT Merryweather) and did a time run. 
The first section starting with ‘for p in page_range’ took 4 mins 51 seconds and 130ms. The section which ran the remove_ocg_from_stream ran in 20ms. 

With a faster pdf (Sotnos), oddly mine ran slower than the time before, taking 1 second, 116 ms, and the for p in page_range took 6 seconds 671 ms.

For a different quick pdf, (Jalie Emilie), it took 5 seconds 372ms for the first bit, and 3 seconds 632ms for the my bit.

Another slow one, SUAT Shirtzie, the first part was 3 min, 11 second, 323ms. My part was 20ms again.

So I’m thinking maybe if yours removes some of the stream, mine runs really quickly? Otherwise mine takes a couple of seconds?

I can see if I can work out what is running slowly in the first part if you like?

Susie

**Comment by cfcurtis** [comment]
Thanks for looking in to this, it's really interesting. I've had some PDFs (Halla mostly, which are weirdly huge) that take forever just to call parse_content_stream, but it's impressive how much faster your function is. I'm not sure if there's something inherently slow about my processing, or if it's just faster the second time after pikepdf has already parsed/unparsed and a bunch of content has been deleted.

Feel free to play around with it, and I will hopefully have some time to look at it as well. I apologize, I've had very little time outside of work lately, and I can't work on it during work hours (though I can comment on github :p).

**Comment by cfcurtis** [comment]
I spent a bit of time on my lunch break looking at this, and I see that you're processing the root object while I'm going through all the pages, so that's probably a source of the difference. What happens if you skip over my loop and just call remove_ocgs? I suspect we need to do both, but there's likely room to improve my implementation.

**Pull request merged**
