### PR TITLE
Big layer update. I tried to merge the two ways of finding the stream…

### PR DESCRIPTION
**Pull request by susiej**
…s into one. It should be a lot more efficient.

Also, I moved wx out of the layer and made some callbacks to update the UI.

### CODE REVIEW

**Comment by mara004** [comment]
This looks very good, thanks! The callbacks are a nice solution.
Only one little thing: Could you please change the two copyright headers of layerfilter and pdfstitcher to MPL?
```
# PDFStitcher is a utility to work with PDF sewing patterns.
# Copyright (C) 2021 Charlotte Curtis
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
```

**Comment by cfcurtis** [comment]
Awesome! I was thinking it would be a good plan to combine the two functions, and popping off empty q/Q blocks is a nice solution as well. I'll merge this in and do some testing then bring it over to main.

**Comment by cfcurtis** [comment]
I just committed a couple of small bug fixes, but I definitely need to dig into this a bit more to really understand it. It's not quite ready for release but I hope it'll end up addressing a number of outlier cases that people keep finding.

A few thoughts so far:
- CMYK support looks to have been dropped
- Deselecting "include non-optional content" no longer does anything (this was a way to remove the content outside of OCGs)
- It feels slower than before, though I haven't done proper timing tests. Not surprising as there's more going on, but it would be good to test.
- One of my test files ended up getting quite a bit bigger, maybe because it's adding a line for every line property definition instead of replacing it? It seemed weird that it would get bigger when I removed content (e.g. one page went from ~2000 lines of commands to ~6000).
- The progress window works nicely

**Comment by susiej** [comment]
Hey,

> I just committed a couple of small bug fixes, but I definitely need to dig into this a bit more to really understand it. It's not quite ready for release but I hope it'll end up addressing a number of outlier cases that people keep finding.
> 
> A few thoughts so far:
> 
> CMYK support looks to have been dropped

I wasn’t sure about the CMYK. If it finds a K, wouldn’t setting RB to the colour chosen be the same thing as converting the RGB colour chosen to K? Or are you selecting CMYK in the colour picker? Does it make a difference to the user if it’s a K or RG? (Not trying to be difficult, I just don’t know). I can convert to K if you think it will make a difference :)

> Deselecting "include non-optional content" no longer does anything (this was a way to remove the content outside of OCGs)
I didn’t know what this did. What do you mean by remove the content outside the OCGs? Do you mean the instructions at the start of the file? I can try to add it back in. :)

> It feels slower than before, though I haven't done proper timing tests. Not surprising as there's more going on, but it would be good to test.
It goes through all the streams in the file rather than just the top level ones. So some files may be slightly slower. But others are much faster as it skips the ones that don’t contain layers. Just timed the Merryweather which I think took about 4 min 51 sec in the previous version just took 23 seconds in this version on my old Thinkpad.


> One of my test files ended up getting quite a bit bigger, maybe because it's adding a line for every line property definition instead of replacing it? It seemed weird that it would get bigger when I removed content (e.g. one page went from ~2000 lines of commands to ~6000).
Bytes are a better thing to go by than lines as some streams are very long. The Merryweather just went from 11MB to 8MB which included adding the stroking properties. Can you give me an example of a file that got bigger so I can look into it? I’ll see if I can shrink the output. I should really update it to remove the line it is replacing rather than just adding a new one to override it! :)  One bit that would add extra lines is when it is restoring the graphics state, but not sure if there is much I can do to help with that. I had to add in the stroking details again or it may restore it to a state with different properties.

> The progress window works nicely
Thanks :)

**Comment by susiej** [comment]
> 
> Deselecting "include non-optional content" no longer does anything (this was a way to remove the content outside of OCGs)

Oh, also, I didn’t intentionally remove this. I just hadn’t tested it.

**Comment by cfcurtis** [comment]
> I wasn’t sure about the CMYK. If it finds a K, wouldn’t setting RB to the colour chosen be the same thing as converting the RGB colour chosen to K? Or are you selecting CMYK in the colour picker? Does it make a difference to the user if it’s a K or RG? (Not trying to be difficult, I just don’t know). I can convert to K if you think it will make a difference :)

I suspect weird things will happen if there's a K command followed by an RG command, but I don't actually know. There may also be a setting somewhere defining which colour space is used for the file. It's much less common, but ultimately I think it's best to just update the colour in the space that's used. 

> Deselecting "include non-optional content" no longer does anything (this was a way to remove the content outside of OCGs)
> I didn’t know what this did. What do you mean by remove the content outside the OCGs? Do you mean the instructions at the start of the file? I can try to add it back in. :)

Some files have content that isn't in OCGs, so when this box is checked it only displayed content from within selected OCGs, rather than removing content from non-selected OCGs. Small difference, but helped in a few places where there was background watermarks and such that made it hard to read.

> It feels slower than before, though I haven't done proper timing tests. Not surprising as there's more going on, but it would be good to test.
> It goes through all the streams in the file rather than just the top level ones. So some files may be slightly slower. But others are much faster as it skips the ones that don’t contain layers. Just timed the Merryweather which I think took about 4 min 51 sec in the previous version just took 23 seconds in this version on my old Thinkpad.

I figured this was the case, it's definitely better to go through all the streams and I like the check to see if OCs are even defined.

> One of my test files ended up getting quite a bit bigger, maybe because it's adding a line for every line property definition instead of replacing it? It seemed weird that it would get bigger when I removed content (e.g. one page went from ~2000 lines of commands to ~6000).
> Bytes are a better thing to go by than lines as some streams are very long. The Merryweather just went from 11MB to 8MB which included adding the stroking properties. Can you give me an example of a file that got bigger so I can look into it? I’ll see if I can shrink the output. I should really update it to remove the line it is replacing rather than just adding a new one to override it! :) One bit that would add extra lines is when it is restoring the graphics state, but not sure if there is much I can do to help with that. I had to add in the stroking details again or it may restore it to a state with different properties.

Good point, I'll have to check the final output size. I was just dumping the content stream to text files to check them out. It was a Jalie pattern that I've been using for a lot of testing. 

Again, thank you so much for your contribution, I think this is going to be a big improvement when it's all ironed out!

**Comment by susiej** [comment]
Hey, I had accidentally left in a line which added more stroke properties than needed, but I see you removed it :). Thanks! I had intended to just have it as the first line in set of oc commands but forgot to update it before committing :p. I have a mild cold so my head was a bit foggy, sorry!. One of the very few downsides of living somewhere without CV19 is still getting colds from your kids :p (not that I’m complaining).

> On 31 May 2021, at 10:35 pm, cfcurtis ***@***.***> wrote:
> 
> ﻿
> I wasn’t sure about the CMYK. If it finds a K, wouldn’t setting RB to the colour chosen be the same thing as converting the RGB colour chosen to K? Or are you selecting CMYK in the colour picker? Does it make a difference to the user if it’s a K or RG? (Not trying to be difficult, I just don’t know). I can convert to K if you think it will make a difference :)
> 
> I suspect weird things will happen if there's a K command followed by an RG command, but I don't actually know. There may also be a setting somewhere defining which colour space is used for the file. It's much less common, but ultimately I think it's best to just update the colour in the space that's used.
> 
Hopefully I’ll get around to fixing that tomorrow. 


> Deselecting "include non-optional content" no longer does anything (this was a way to remove the content outside of OCGs)
> I didn’t know what this did. What do you mean by remove the content outside the OCGs? Do you mean the instructions at the start of the file? I can try to add it back in. :)
> 
> Some files have content that isn't in OCGs, so when this box is checked it only displayed content from within selected OCGs, rather than removing content from non-selected OCGs. Small difference, but helped in a few places where there was background watermarks and such that made it hard to read.
> 
Do you have an example of a PDF I can test with? I have quite a few PDF patterns. If I don’t have one from that designer, I’ll see if they have a free one.

**Comment by cfcurtis** [comment]
> Hey, I had accidentally left in a line which added more stroke properties than needed, but I see you removed it :). Thanks! I had intended to just have it as the first line in set of oc commands but forgot to update it before committing :p. I have a mild cold so my head was a bit foggy, sorry!. One of the very few downsides of living somewhere without CV19 is still getting colds from your kids :p (not that I’m complaining).

Wow, that's pretty great! Not the cold part, but the no covid part. We're still fairly restricted in Canada.

> Do you have an example of a PDF I can test with? I have quite a few PDF patterns. If I don’t have one from that designer, I’ll see if they have a free one.

Jalie again is one that has "non-optional" content, though I did some testing at lunchtime and it looks like the images are all removed no matter what. I think maybe we need to add some checks to see if the stream is actually a content stream, because "pikepdf.Stream" can be one of 3 different things (https://pikepdf.readthedocs.io/en/latest/topics/streams.html). I keep getting warnings about trying to parse an unsupported stream as well.

I think too that some of the speed differences I'm seeing have to do with how the pages are parsed. I did some timing and on my "fast" computer it was 7 seconds for the old code and 14 for the new. If you call parse_content_stream on a page object that has an array of content streams, it will collapse all of the array items and spit out a single list of operators using C++ optimized code that seems to be faster than parsing each array item individually. This also makes it so you don't need to keep track of OCGs that split across streams because one page would generate one stream. On the other hand, it's probably more memory efficient to do it your way, so that could have advantages. Something to think about, anyway.

**Comment by cfcurtis** [comment]
I've been working on some changes to address some of the things I noticed, but it's not quite working yet so I'm not pushing changes. I'd draft a pull request but apparently I can't do that as the owner of the repo!

**Pull request merged**
