### PR TITLE
Fix missing whitespaces in `content_txt`

### PR DESCRIPTION
**Pull request by mara004**
Fixes the bug described under #46 and d31bec4
The problematic line was hard to notice but once you look at it in detail the cause of the issue is pretty obvious.

### CODE REVIEW

**Comment by mara004** [comment]
Hmm, somehow it mixed up the git history again - I hope this is not a problem?

**Review by cfcurtis — CHANGES_REQUESTED** [review]
My apologies, it's because I split off the changes to layerfilter (and associated things in pdfstitcher.py) to a new dev branch. Can you re-submit with just the tile_pages.py changes?

**Comment by mara004** [comment]
Sure, I could try, but maybe it's easiest if you could just commit it directly; the required change is so small.

**Comment by cfcurtis** [comment]
Sure, I just pushed it. I put the whitespace at the end of both lines because that's how it was before (not sure how I accidentally got rid of them).

**Comment by mara004** [comment]
Thanks!

**Pull request closed without merging**
