### PR TITLE
Separate LayerFilter processing and GUI components

### PR DESCRIPTION
**Pull request by mara004**
This is the second try. I believe I have used the latest layerfilter.py - if not, please complain.
I tested it with the free isolation gown pattern and things still seem to work.
However, the if checks in WxLayerFilter are probably not the cleanest solution. It might have been better to set the progress bar range beforehand and retrieve the output afterwards rather than yielding it. What do you think?
Also, I'm surprised the progress pop-up really needs to be closed for the document to be saved - did I introduce this with my modifications, or was it already like this before?

### CODE REVIEW

**Comment by mara004** [comment]
I just noticed it's the wrong license headers - I'll correct that...

**Comment by cfcurtis** [comment]
I think these changes might have introduced the issue with the pop-up window, it's not doing that on my version. Do you mind if I wait to merge this for a few days? I'm about to head off camping so I won't be able to look at it anyway.

**Comment by mara004** [comment]
Sure. Enjoy your camping!
In the meantime, I'll try to look into the pop-up window thing.

**Comment by mara004** [comment]
Oh, I see @susiej solved the problem in a cleaner way with #77, so this PR can be closed I think.

**Pull request closed without merging**
