### PR TITLE
If we are deleting layers, also remove them from content streams

### PR DESCRIPTION
**Pull request by susiej**

### CODE REVIEW

**Comment by cfcurtis** [comment]
So, I tried originally just to remove the OCs from the stream, but I kept getting q/Q errors in various files that had ugly structure where an opening q was inside an OCG but the closing one was outside, or where the properties for one layer relied on a definition in another. That's why I ended up with the messy solution of keeping all non-displaying content. That said, if this works I think it's way better - have you tested on a number of different files?

**Comment by susiej** [comment]
Tried two different ones that had completely different structures. I’ll try more when I get home. The name of the ocg in the stream is different to the name in the ocg file and you need to look them up. Which designer made one that seemed broken? I’ll see if I have one of their files.

**Comment by cfcurtis** [comment]
Do you mean the /MC# name, or something different? I am retrieving the name in the stream in find_page_keep, but there might be something I'm missing.

One that I used a lot for testing was Jalie 2679, I think it had that weird glitch.

**Comment by susiej** [comment]
Umm I’m not sure about /MC. In the pdf I was editing it had Pr1 as the name of one of the layers in the stream, then you looked up the resource properties and it had /Pr1 18 0 R which is a reference to the 18 0 R object which has the real name of something like ’Size 3’.

Hrm, the free Jalie one (Jalie 3896) doesn’t seem to work. I’ll see if I can figure out what is breaking. :)

**Comment by susiej** [comment]
Ah MC is the same as Pr I think.

The Q/q issue in Jalie patterns is nasty. In adobe, if I ignore the imbalance, then it generates an error. If I fix it along the way, it generates a blank page. Weirdly both ways open correctly in preview. I’ll keep looking

**Comment by cfcurtis** [comment]
That's probably it, for some reason most of the test files I've checked use MC but it must be dependent on the generating software.

I'm going to merge in the changes so we can keep working on this (though I unfortunately have another project on the go and can't really spend much time on this until next week). There's a couple of things I'd like to address specifically:

- In addition to the q/Q mismatch, things like line colour/thickness and font size can be defined in one layer and propagated through to the next, so removing the content without checking for this could cause unexpected results.
- I'd like to avoid looping through the content stream twice (once for line properties, once to remove layers). It's shockingly slow sometimes.

For detecting errors I've found ghostscript to give the most useful error messages.

**Comment by cfcurtis** [comment]
@susiej I split this off into a branch layer_filter_improvements so I can make a new release soon with some other changes while we still test this part.

**Pull request closed without merging**
